import React from 'react';
import type { Metadata } from "next";
import type { ReactNode } from 'react';
import localFont from 'next/font/local';
import "./globals.css";

const inter = localFont({
  src: './fonts/Inter/Inter-VariableFont_opsz,wght.ttf',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Hello Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}